import { ChevronLeft, ChevronRight, Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useListCustomers, useListOrders, useListProducts } from '@workspace/api-client-react';
import type { Customer, Order, Product } from '@workspace/api-client-react';
import { EmptyState, ErrorState, PageHeader, SkeletonRows, StatusPill } from '@/components/console-layout';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const date = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' });

function SearchBar({ value, onChange, placeholder, testId }: { value: string; onChange: (value: string) => void; placeholder: string; testId: string }) {
  return <div className="flex w-full items-center gap-3 rounded-md border border-input bg-card px-3 py-2.5 focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/10 md:max-w-[420px]"><Search size={16} className="text-muted-foreground" /><input data-testid={testId} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground/70" /><span className="hidden font-mono-ui text-[9px] text-muted-foreground/70 sm:inline">buscar</span></div>;
}

function Pager({ page, totalPages, onPage }: { page: number; totalPages: number; onPage: (page: number) => void }) {
  return <div className="flex items-center justify-between border-t border-border px-5 py-3"><div className="font-mono-ui text-[10px] text-muted-foreground">página {page} de {totalPages || 1}</div><div className="flex gap-1"><button data-testid="button-page-previous" onClick={() => onPage(Math.max(1, page - 1))} disabled={page <= 1} className="rounded-md border border-border p-1.5 text-muted-foreground hover:bg-muted disabled:cursor-not-allowed disabled:opacity-35"><ChevronLeft size={15} /></button><button data-testid="button-page-next" onClick={() => onPage(Math.min(totalPages || 1, page + 1))} disabled={page >= (totalPages || 1)} className="rounded-md border border-border p-1.5 text-muted-foreground hover:bg-muted disabled:cursor-not-allowed disabled:opacity-35"><ChevronRight size={15} /></button></div></div>;
}

function TableFrame({ children, header, loading, empty, error, onRetry, footer }: { children: React.ReactNode; header: React.ReactNode; loading: boolean; empty: boolean; error: boolean; onRetry: () => void; footer: React.ReactNode }) {
  return <div className="card-surface overflow-hidden"><div className="hidden min-w-[760px] md:block"><div className="grid border-b border-border bg-muted/45 px-5 py-3 font-mono-ui text-[9px] uppercase tracking-[.12em] text-muted-foreground">{header}</div>{loading ? <SkeletonRows count={7} cols={5} /> : error ? <ErrorState onRetry={onRetry} /> : empty ? <EmptyState label="Nenhum registro encontrado" detail="Ajuste o termo de busca ou limpe os filtros para consultar o cadastro completo." /> : children}</div><div className="md:hidden">{loading ? <SkeletonRows count={5} cols={2} /> : error ? <ErrorState onRetry={onRetry} /> : empty ? <EmptyState label="Nenhum registro encontrado" detail="Ajuste sua busca." /> : children}</div>{footer}</div>;
}

export function CustomersPage() {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const params = useMemo(() => ({ page, pageSize: 10, search: search || undefined }), [page, search]);
  const query = useListCustomers(params);
  const rows = query.data?.data ?? [];
  return <><PageHeader eyebrow="cadastro mestre / 02" title="Clientes" description="Consulte o cadastro de clientes sincronizado com o ambiente Protheus." action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal size={15} /> somente leitura</div>} /><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><SearchBar value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Nome, código ou documento..." testId="input-search-customers" /><span className="font-mono-ui text-[10px] text-muted-foreground">{query.data?.pagination.total ?? '—'} registros</span></div><TableFrame loading={query.isLoading} error={query.isError} empty={!query.isLoading && rows.length === 0} onRetry={() => void query.refetch()} footer={<Pager page={page} totalPages={query.data?.pagination.totalPages ?? 1} onPage={setPage} />} header={<><div>Código / cliente</div><div>Documento</div><div>Localização</div><div>Status</div><div className="text-right">Receita acumulada</div></>}>{<div className="divide-y divide-border">{rows.map((customer: Customer) => <div key={customer.id} data-testid={`row-customer-${customer.id}`} className="grid min-w-[760px] items-center gap-4 px-5 py-3.5 text-[12px] md:grid-cols-5"><div><div className="font-mono-ui text-[10px] text-primary">{customer.code}</div><div className="mt-1 font-semibold">{customer.name}</div></div><div className="font-mono-ui text-[11px] text-muted-foreground">{customer.document}</div><div><div>{customer.city}</div><div className="mt-0.5 font-mono-ui text-[10px] text-muted-foreground">{customer.state}</div></div><div><StatusPill status={customer.status} tone={customer.status === 'Ativo' ? 'good' : 'neutral'} /></div><div className="text-right font-mono-ui text-[11px] font-medium">{money.format(customer.revenue)}</div></div>)}</div>}</TableFrame></>;
}

export function ProductsPage() {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const params = useMemo(() => ({ page, pageSize: 10, search: search || undefined }), [page, search]);
  const query = useListProducts(params);
  const rows = query.data?.data ?? [];
  return <><PageHeader eyebrow="cadastro mestre / 03" title="Produtos" description="Veja disponibilidade, preço e estado do catálogo comercial em tempo real." action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal size={15} /> somente leitura</div>} /><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><SearchBar value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Nome, código ou categoria..." testId="input-search-products" /><span className="font-mono-ui text-[10px] text-muted-foreground">{query.data?.pagination.total ?? '—'} registros</span></div><TableFrame loading={query.isLoading} error={query.isError} empty={!query.isLoading && rows.length === 0} onRetry={() => void query.refetch()} footer={<Pager page={page} totalPages={query.data?.pagination.totalPages ?? 1} onPage={setPage} />} header={<><div>Código / produto</div><div>Categoria</div><div>Unidade</div><div>Disponibilidade</div><div className="text-right">Preço unitário</div></>}>{<div className="divide-y divide-border">{rows.map((product: Product) => <div key={product.id} data-testid={`row-product-${product.id}`} className="grid min-w-[760px] items-center gap-4 px-5 py-3.5 text-[12px] md:grid-cols-5"><div><div className="font-mono-ui text-[10px] text-primary">{product.code}</div><div className="mt-1 font-semibold">{product.name}</div></div><div className="text-muted-foreground">{product.category}</div><div className="font-mono-ui text-[11px]">{product.unit}</div><div><div className="font-mono-ui text-[11px]">{product.stock.toLocaleString('pt-BR')} un.</div><div className="mt-1"><StatusPill status={product.status} tone={product.status === 'Ativo' ? 'good' : 'bad'} /></div></div><div className="text-right font-mono-ui text-[11px] font-medium">{money.format(product.price)}</div></div>)}</div>}</TableFrame></>;
}

export function OrdersPage() {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const params = useMemo(() => ({ page, pageSize: 10, search: search || undefined }), [page, search]);
  const query = useListOrders(params);
  const rows = query.data?.data ?? [];
  return <><PageHeader eyebrow="documentos comerciais / 04" title="Pedidos de venda" description="Acompanhe documentos emitidos e pendências do fluxo comercial do Protheus." action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal size={15} /> somente leitura</div>} /><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><SearchBar value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Número, cliente ou status..." testId="input-search-orders" /><span className="font-mono-ui text-[10px] text-muted-foreground">{query.data?.pagination.total ?? '—'} registros</span></div><TableFrame loading={query.isLoading} error={query.isError} empty={!query.isLoading && rows.length === 0} onRetry={() => void query.refetch()} footer={<Pager page={page} totalPages={query.data?.pagination.totalPages ?? 1} onPage={setPage} />} header={<><div>Número</div><div>Cliente</div><div>Emissão</div><div>Status</div><div className="text-right">Total</div></>}>{<div className="divide-y divide-border">{rows.map((order: Order) => <div key={order.id} data-testid={`row-order-${order.id}`} className="grid min-w-[760px] items-center gap-4 px-5 py-3.5 text-[12px] md:grid-cols-5"><div><div className="font-mono-ui text-[11px] font-medium text-primary">#{order.number}</div><div className="mt-1 font-mono-ui text-[10px] text-muted-foreground">{order.items} itens</div></div><div className="font-medium">{order.customer}</div><div className="font-mono-ui text-[10px] text-muted-foreground">{date.format(new Date(order.date))}</div><div><StatusPill status={order.status} tone={order.status === 'Faturado' ? 'good' : order.status === 'Pendente' ? 'warn' : 'bad'} /></div><div className="text-right font-mono-ui text-[11px] font-medium">{money.format(order.total)}</div></div>)}</div>}</TableFrame></>;
}